name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 7 * * *' # once a day at 7 AM
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: noufath/blog-post-workflow@master
        with:
          feed_list: "https://danynotes.github.io/feed.xml"